import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../lib/api';
import { saveInsight } from '../lib/insightStore';

const statusClass = { HIGHLY_ENGAGED:'high', ENGAGED:'engaged', NEEDS_ATTENTION:'attention', AT_RISK:'risk' };
const statusLabel = s => s?.replace('_',' ').replace('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const fmtDate = d => d ? new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(new Date(d)) : 'No activity';
const recent = d => { if(!d) return 'No activity'; const days=Math.floor((Date.now()-new Date(d))/86400000); return days===0?'Today':days===1?'Yesterday':`${days} days ago`; };

export default function Dashboard(){
 const [dashboard,setDashboard]=useState(null), [students,setStudents]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState('');
 const [search,setSearch]=useState(''),[status,setStatus]=useState('ALL'),[riskOnly,setRiskOnly]=useState(false); const navigate=useNavigate();
 const [ai,setAi]=useState(null),[aiLoading,setAiLoading]=useState(false),[aiError,setAiError]=useState(''),[aiFallback,setAiFallback]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const [d,s]=await Promise.all([api.get('/dashboard'),api.get('/students')]);setDashboard(d.data);setStudents(s.data.students||[])}catch(e){setError(e.response?.data?.message||'Could not load student engagement data. Please check the API connection.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const generateInsight=async()=>{if(aiLoading)return;setAiLoading(true);setAiError('');try{const r=await api.post('/ai/dashboard-insight');setAi(r.data.insight);setAiFallback(Boolean(r.data.fallback));saveInsight({type:'dashboard',title:'Dashboard insight',insight:r.data.insight})}catch(e){setAiError(e.response?.data?.message||'Could not generate dashboard insight.')}finally{setAiLoading(false)}};
 const filtered=useMemo(()=>students.filter(s=>{const matchName=s.name.toLowerCase().includes(search.toLowerCase());const matchStatus=status==='ALL'||s.status===status;const matchRisk=!riskOnly||s.status==='AT_RISK';return matchName&&matchStatus&&matchRisk}),[students,search,status,riskOnly]);
 if(loading)return <Loading/>; if(error)return <div className="state-card"><h2>Something went wrong</h2><p>{error}</p><button className="primary-btn" onClick={load}>Try again</button></div>;
 const kpis=[['Total Students',dashboard?.totalStudents,'All learners'],['Active Students',dashboard?.activeStudents,'Active in last 7 days'],['At-Risk Students',dashboard?.atRiskStudents,'Needs follow-up'],['Average Engagement',`${dashboard?.averageEngagement??0}%`,'Across all students'],['Average Quiz Score',`${dashboard?.averageQuizScore??0}%`,'Current performance']];
 return <div className="dashboard-page">
  <div className="page-intro"><div><p className="eyebrow">ENGAGEMENT OVERVIEW</p><h1>Hello, teacher</h1><p>Monitor engagement and quickly spot learners who need support.</p></div><button className="secondary-btn" onClick={load}>Refresh data</button></div>
  <div className="kpi-grid">{kpis.map(([title,value,sub])=><article className="kpi-card" key={title}><span>{title}</span><strong>{value??0}</strong><small>{sub}</small></article>)}</div>
  <section className="panel ai-card dashboard-ai-card"><div className="ai-card-head"><div><p className="eyebrow">AI INSIGHTS</p><h2>Class engagement summary</h2><p>Grounded in current dashboard metrics. Engagement scores remain backend-calculated.</p></div><button className="primary-btn" onClick={generateInsight} disabled={aiLoading}>{aiLoading?'Generating…':ai?'Regenerate':'Generate AI Insight'}</button></div>
   <div className="ai-dashboard-metrics"><span><b>{dashboard?.atRiskStudents??0}</b> at-risk students</span><span><b>{dashboard?.averageEngagement??0}%</b> average engagement</span></div>
    {aiError&&<div className="ai-error">{aiError}</div>}{aiFallback&&!aiLoading&&<div className="ai-error">Automated data-based fallback, not AI-generated. Gemini was unavailable, so this insight uses backend metrics.</div>}{aiLoading&&<div className="ai-loading"><span/><span/><span/></div>}
   {ai&&!aiLoading&&<div className="ai-dashboard-result"><div><h3>Overall summary</h3><p>{ai.summary}</p></div><div><h3>Important trend</h3><p>{ai.importantTrend}</p></div><div><h3>Recommended teacher action</h3><p>{ai.recommendedAction}</p></div>{ai.keyObservations?.length>0&&<div><h3>Key observations</h3><ul className="ai-list">{ai.keyObservations.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}</div>}
  </section>
  <section className="panel students-panel"><div className="panel-heading"><div><h2>Student engagement</h2><p>{filtered.length} of {students.length} students shown</p></div><div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search student…" aria-label="Search students"/><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter status"><option value="ALL">All status</option><option value="HIGHLY_ENGAGED">Highly Engaged</option><option value="ENGAGED">Engaged</option><option value="NEEDS_ATTENTION">Needs Attention</option><option value="AT_RISK">At Risk</option></select><button className={riskOnly?'risk-filter active':'risk-filter'} onClick={()=>setRiskOnly(!riskOnly)}>At Risk only</button></div></div>
   {filtered.length===0?<div className="empty-state"><strong>No students found</strong><p>Try changing your search or filters.</p><button className="text-btn" onClick={()=>{setSearch('');setStatus('ALL');setRiskOnly(false)}}>Clear filters</button></div>:<><div className="student-table-wrap"><table><thead><tr><th>Student</th><th>Engagement</th><th>Status</th><th>Last Active</th><th>Assignment Completion</th><th>Quiz Score</th><th>Recent Activity</th></tr></thead><tbody>{filtered.map(s=><tr key={s.id} onClick={()=>navigate(`/students/${s.id}`)} tabIndex="0"><td><div className="student-name"><span>{s.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><b>{s.name}</b></div></td><td><div className="score"><i><em style={{width:`${s.engagementScore}%`}}/></i>{s.engagementScore}%</div></td><td><span className={`status ${statusClass[s.status]||''}`}>{statusLabel(s.status)}</span></td><td>{fmtDate(s.lastActive)}</td><td>{s.assignmentCompletion}%</td><td>{s.quizScore}%</td><td>{recent(s.lastActive)}</td></tr>)}</tbody></table></div><div className="mobile-students">{filtered.map(s=><button key={s.id} onClick={()=>navigate(`/students/${s.id}`)} className="student-mobile-card"><div><b>{s.name}</b><span>{recent(s.lastActive)}</span></div><div><strong>{s.engagementScore}%</strong><span className={`status ${statusClass[s.status]||''}`}>{statusLabel(s.status)}</span></div><small>Assignments {s.assignmentCompletion}% · Quiz {s.quizScore}%</small></button>)}</div></>}
  </section>
 </div>
}
function Loading(){return <div className="dashboard-page"><div className="skeleton intro"/><div className="kpi-grid">{Array.from({length:5}).map((_,i)=><div className="skeleton kpi" key={i}/>)}</div><div className="skeleton table-skeleton"/></div>}
