import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../lib/api';
const statusClass={HIGHLY_ENGAGED:'high',ENGAGED:'engaged',NEEDS_ATTENTION:'attention',AT_RISK:'risk'};
const label=s=>s?.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const fmt=d=>d?new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(new Date(d)):'No activity';
export default function Students(){
 const [students,setStudents]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [search,setSearch]=useState(''),[status,setStatus]=useState('ALL'),[riskOnly,setRiskOnly]=useState(false); const navigate=useNavigate();
 const load=async()=>{setLoading(true);setError('');try{const r=await api.get('/students');setStudents(r.data.students||[])}catch(e){setError(e.response?.data?.message||'Could not load students.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>students.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())&&(status==='ALL'||s.status===status)&&(!riskOnly||s.status==='AT_RISK')),[students,search,status,riskOnly]);
 const clear=()=>{setSearch('');setStatus('ALL');setRiskOnly(false)};
 if(loading)return <div className="dashboard-page"><div className="skeleton intro"/><div className="skeleton table-skeleton"/></div>;
 if(error)return <div className="state-card"><h2>Students unavailable</h2><p>{error}</p><button className="primary-btn" onClick={load}>Try again</button></div>;
 return <div className="dashboard-page"><div className="page-intro"><div><p className="eyebrow">STUDENT DIRECTORY</p><h1>Students</h1><p>Search engagement and open any learner profile.</p></div><button className="secondary-btn" onClick={load}>Refresh data</button></div>
 <section className="panel students-panel"><div className="panel-heading"><div><h2>All students</h2><p>{filtered.length} of {students.length} students shown</p></div><div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search student…" aria-label="Search students"/><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter status"><option value="ALL">All status</option><option value="HIGHLY_ENGAGED">Highly Engaged</option><option value="ENGAGED">Engaged</option><option value="NEEDS_ATTENTION">Needs Attention</option><option value="AT_RISK">At Risk</option></select><button className={riskOnly?'risk-filter active':'risk-filter'} onClick={()=>setRiskOnly(!riskOnly)}>At Risk only</button></div></div>
 {filtered.length===0?<div className="empty-state"><strong>No students found</strong><p>Try changing your search or filters.</p><button className="text-btn" onClick={clear}>Clear filters</button></div>:<><div className="student-table-wrap"><table><thead><tr><th>Student</th><th>Engagement</th><th>Status</th><th>Last Active</th><th>Assignment Completion</th><th>Quiz Score</th></tr></thead><tbody>{filtered.map(s=><tr key={s.id} onClick={()=>navigate(`/students/${s.id}`)} onKeyDown={e=>e.key==='Enter'&&navigate(`/students/${s.id}`)} tabIndex="0"><td><div className="student-name"><span>{s.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><b>{s.name}</b></div></td><td><div className="score"><i><em style={{width:`${s.engagementScore}%`}}/></i>{s.engagementScore}%</div></td><td><span className={`status ${statusClass[s.status]||''}`}>{label(s.status)}</span></td><td>{fmt(s.lastActive)}</td><td>{s.assignmentCompletion}%</td><td>{s.quizScore}%</td></tr>)}</tbody></table></div><div className="mobile-students">{filtered.map(s=><button key={s.id} className="student-mobile-card" onClick={()=>navigate(`/students/${s.id}`)}><div><b>{s.name}</b><span>{fmt(s.lastActive)}</span></div><div><strong>{s.engagementScore}%</strong><span className={`status ${statusClass[s.status]||''}`}>{label(s.status)}</span></div><small>Assignments {s.assignmentCompletion}% · Quiz {s.quizScore}%</small></button>)}</div></>}</section></div>
}
